# fly.toml app configuration file generated for ashastass on 2026-08-25T10:23:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ashastass'
primary_region = 'lhr'

[build]
[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
