[project]
name = "asha-iris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "fastmcp>=3.4.5",
    "openai-agents>=0.19.1",
    "paho-mqtt>=2.1.0",
    "python-telegram-bot>=22.8",
    "redis>=8.0.1",
]
